gcp:
  project_id: "abemcomum-saev-prod"
  region: "us-central1"
  network: "default"
  subnetwork: "default"
  bucket_name: "gs://abemcomum-saev-prod"

artefact_registry:
  repository: "dataflow-templates"
  location: "us-central1"
  image_name: "mysql-to-bq-dataflow-multiple-tables"

dataflow:
  job_name: "mysql-to-bq-dataflow-multiple-tables-ingestion" 
  template_file_name: "mysql-to-bq-dataflow-multiple-tables-template.json"
  parameters:
    sdk_container_image: ""
    temp_location: "gs://abemcomum-saev-prod/mysql-to-bq-dataflow-multiple-tables/temp"
    staging_location: "gs://abemcomum-saev-prod/mysql-to-bq-dataflow-multiple-tables/staging"
    machine_type: "n1-standard-1"
    runner: "DataflowRunner"

# Credenciais do banco de dados de origem
source_db:
  secret_id: "dataflow-mysql-credentials"
  secret_version: "latest"

# Dataset de destino no BigQuery
destination_dataset: "bronze"

# Lista de tabelas para ingestão
tables:
  - name: "genero"
    query_file: "genero.sql"
    schema_file: "genero.json"
    write_disposition: "WRITE_TRUNCATE"
    map_function: "map_genero_to_dict"

  - name: "raca"
    query_file: "raca.sql"
    schema_file: "raca.json"
    write_disposition: "WRITE_TRUNCATE"
    map_function: "map_raca_to_dict"