gcp:
  project_id: abemcomum-saev-prod
  region: us-central1
  network: default
  subnetwork: default
  bucket_name: gs://abemcomum-saev-prod
artefact_registry:
  repository: dataflow-templates
  location: us-central1
  image_name: mysql-to-bq-dataflow-multiple-tables
database:
  driver_class_name: com.mysql.cj.jdbc.Driver
  driver_jars: _drivers/mysql-connector-j-8.0.33.jar
dataflow:
  job_name: test-mysql-to-bq-multiple-ingestion-local-job
  template_file_name: '{{ artefact_registry.image_name }}-template.json'
  parameters:
    sdk_container_image: ''
    temp_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/temp'
    staging_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/staging'
    queries_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/queries'
    schemas_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/schemas'
    landing_zone_gcs_path_table: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name
      }}/landing_zone'
    runner: DirectRunner
    machine_type: n1-standard-1
source_db:
  secret_id: dataflow-mysql-credentials
  secret_version: 1
landing_zone_dataset: landing_zone
bronze_dataset: bronze
silver_dataset: silver
gold_dataset: gold
region: US
watermark_table:
  dataset_id: meta_controle
  table_id: watermarks
tables:
- name: genero
  query_file: genero.sql
  schema_file: genero.json
  delta_config:
    column: GEN_DT_ATUALIZACAO
    type: TIMESTAMP
  merge_config:
    keys:
    - GEN_ID
  partitioning_config:
    type: DAY
    column: GEN_DT_ATUALIZACAO
  clustering_config:
    columns:
    - GEN_ID
    - GEN_ATIVO
- name: raca
  query_file: raca.sql
  schema_file: raca.json
  delta_config:
    column: PEL_DT_ATUALIZACAO
    type: TIMESTAMP
  merge_config:
    keys:
    - PEL_ID
  partitioning_config:
    type: DAY
    column: PEL_DT_ATUALIZACAO
  clustering_config:
    columns:
    - PEL_ID
    - PEL_ATIVO
    - PEL_OLD_ID
chunks:
- name: ALL
  lista:
  - genero
  - raca
- name: genero
  lista:
  - genero
- name: raca
  lista:
  - raca
