gcp:
  project_id: abemcomum-saev-prod
  region: us-central1
  network: default
  subnetwork: default
  bucket_name: gs://abemcomum-saev-prod

artefact_registry:
  repository: dataflow-templates
  location: us-central1
  image_name: mysql-to-bq-dataflow-multiple-tables

database:
  driver_class_name: com.mysql.cj.jdbc.Driver
  driver_jars: _drivers/mysql-connector-j-8.0.33.jar

dataflow:
  job_name: '{{ artefact_registry.image_name }}-ingestion'
  template_file_name: '{{ artefact_registry.image_name }}-template.json'
  parameters:
    sdk_container_image: ''
    temp_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/temp'
    staging_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/staging'
    queries_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/queries'
    schemas_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/schemas'
    landing_zone_gcs_path_table: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/landing_zone'
    runner: DataflowRunner    
    # Parâmetros adicionais para otimização
    machine_type: n1-standard-1
    # machine_type: "n1-standard-2"
    # num_workers: 1
    # max_num_workers: 5

# Credenciais do banco de dados de origem
source_db:
  secret_id: dataflow-mysql-credentials
  secret_version: latest

# Dataset de destino no BigQuery
landing_zone_dataset: landing_zone
bronze_dataset: bronze
silver_dataset: silver
gold_dataset: gold

# Tabela de controle para o processo incremental
watermark_table:
  dataset_id: 'meta_controle'
  table_id: 'watermarks'

# Lista de tabelas para ingestão
tables:
  - name: genero
    query_file: genero.sql
    schema_file: genero.json
    write_disposition: WRITE_TRUNCATE
    map_function: map_genero_to_dict
    watermark_column: GEN_DT_ATUALIZACAO
    landing_zone_gcs_path_table: gs://abemcomum-saev-prod/landing_zone/genero

  - name: raca
    query_file: raca.sql
    schema_file: raca.json
    write_disposition: WRITE_TRUNCATE
    map_function: map_raca_to_dict
    watermark_column: PEL_DT_ATUALIZACAO
    landing_zone_gcs_path_table: gs://abemcomum-saev-prod/landing_zone/raca
    
# Chunks de tabelas para ingestão
chunks:
  - name: ALL
    lista: [genero, raca]
  - name: genero
    lista: [genero]
  - name: raca
    lista: [raca]