gcp:
  project_id: abemcomum-saev-prod
  region: us-central1
  # region: US
  network: default
  subnetwork: default
  bucket_name: gs://abemcomum-saev-prod

artefact_registry:
  repository: dataflow-templates
  location: us-central1
  image_name: mysql-to-bq-dataflow-multiple-tables

database:
  driver_class_name: com.mysql.cj.jdbc.Driver
  driver_jars: _drivers/mysql-connector-j-8.0.33.jar

dataflow:
  job_name: '{{ artefact_registry.image_name }}-ingestion'
  template_file_name: '{{ artefact_registry.image_name }}-template.json'
  parameters:
    sdk_container_image: ''
    temp_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/temp'
    staging_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/staging'
    queries_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/queries'
    schemas_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/schemas'
    landing_zone_gcs_path_table: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/landing_zone'
    runner: DataflowRunner    
    # Parâmetros adicionais para otimização
    machine_type: n1-standard-1
    # machine_type: "n1-standard-2"
    # num_workers: 1
    # max_num_workers: 5

# Credenciais do banco de dados de origem
source_db:
  secret_id: dataflow-mysql-credentials
  secret_version: latest

# Dataset de destino no BigQuery
landing_zone_dataset: landing_zone
bronze_dataset: bronze
silver_dataset: silver
gold_dataset: gold
region: US

# Tabela de controle para o processo incremental
watermark_table:
  dataset_id: 'meta_controle'
  table_id: 'watermarks'

# Lista de tabelas para ingestão
tables:
  - name: genero
    query_file: genero.sql
    schema_file: genero.json
    delta_config:
      column: GEN_DT_ATUALIZACAO
      type: TIMESTAMP
    merge_config:
      keys:
        - GEN_ID
    partitioning_config:
      type: DAY
      column: GEN_DT_ATUALIZACAO
    clustering_config:
      columns: 
        - GEN_ID
        - GEN_ATIVO

  - name: raca
    query_file: raca.sql
    schema_file: raca.json
    delta_config:
      column: PEL_DT_ATUALIZACAO
      type: TIMESTAMP
    merge_config:
      keys:
        - PEL_ID
    partitioning_config:
      type: DAY
      column: PEL_DT_ATUALIZACAO
    clustering_config:
      columns: 
        - PEL_ID
        - PEL_ATIVO
        - PEL_OLD_ID
    
# Chunks de tabelas para ingestão
chunks:
  - name: ALL
    lista: [aluno_teste_resposta, aluno_teste_resposta_historico, aluno_teste, report_question, report_descriptor, report_race, turma_aluno, aluno, report_subject, report_not_evaluated, infrequencia, notifications, report_edition, transferencia, turma, avaliacao_municipio, forget_password, aluno_alu_deficiencias_pcd, usuario, messages_schools_escola, teste_gabarito, turma_professor, job, escola, professor, matriz_referencia_topico_items, envios_tutor_mensagens, microdata, teste, messages_municipios_municipio, avaliacao_teste, matriz_referencia_topico, sub_perfil_area, importar_dados, regionais, municipio, matriz_referencia_serie, avaliacao, messages, matriz_referencia, avaliacao_online_question_alternative, series, migrations, area, pcd, ano_letivo, estados, tutor_mensagens, avaliacao_online_question, avaliacao_online_page, sub_perfil, formacao, raca, disciplina, perfil_base, genero, templates_mensagens, report_question_option, dados, avaliacao_online, arquivo, external_reports]
  - name: TABELAS_PEQUENAS
    lista: [turma_professor, job, escola, professor, matriz_referencia_topico_items, envios_tutor_mensagens, microdata, teste, messages_municipios_municipio, avaliacao_teste, matriz_referencia_topico, sub_perfil_area, importar_dados, regionais, municipio, matriz_referencia_serie, avaliacao, messages, matriz_referencia, avaliacao_online_question_alternative, series, migrations, area, pcd, ano_letivo, estados, tutor_mensagens, avaliacao_online_question, avaliacao_online_page, sub_perfil, formacao, raca, disciplina, perfil_base, genero, templates_mensagens, report_question_option, dados, avaliacao_online, arquivo, external_reports]
  - name: TABELAS_MEDIAS
    lista: [avaliacao_municipio, forget_password, aluno_alu_deficiencias_pcd, usuario, messages_schools_escola, teste_gabarito]
  - name: turma
    lista: [turma]
  - name: transferencia
    lista: [transferencia]
  - name: report_edition
    lista: [report_edition]
  - name: notifications
    lista: [notifications]
  - name: infrequencia
    lista: [infrequencia]
  - name: report_not_evaluated
    lista: [report_not_evaluated]
  - name: report_subject
    lista: [report_subject]
  - name: aluno
    lista: [aluno]
  - name: turma_aluno
    lista: [turma_aluno]
  - name: report_race
    lista: [report_race]
  - name: report_descriptor
    lista: [report_descriptor]
  - name: report_question
    lista: [report_question]
  - name: aluno_teste
    lista: [aluno_teste]
  - name: aluno_teste_resposta_historico
    lista: [aluno_teste_resposta_historico]
  - name: aluno_teste_resposta
    lista: [aluno_teste_resposta]
  
    