gcp:
  project_id: abemcomum-saev-prod
  region: us-central1
  network: default
  subnetwork: default
  bucket_name: gs://abemcomum-saev-prod

artefact_registry:
  repository: dataflow-templates
  location: us-central1
  image_name: mysql-to-bq-dataflow-multiple-tables

database:
  driver_class_name: com.mysql.cj.jdbc.Driver
  driver_jars: _drivers/mysql-connector-j-8.0.33.jar

dataflow:
  job_name: '{{ artefact_registry.image_name }}-ingestion'
  template_file_name: '{{ artefact_registry.image_name }}-template.json'
  parameters:
    sdk_container_image: ''
    temp_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/temp'
    staging_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/staging'
    queries_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/queries'
    schemas_location: '{{ gcp.bucket_name }}/{{ artefact_registry.image_name }}/schemas'
    machine_type: n1-standard-1
    runner: DataflowRunner

# Credenciais do banco de dados de origem
source_db:
  secret_id: dataflow-mysql-credentials
  secret_version: latest

# Dataset de destino no BigQuery
destination_dataset: bronze

# Lista de tabelas para ingestão
tables:
  - name: genero
    query_file: genero.sql
    schema_file: genero.json
    write_disposition: WRITE_TRUNCATE
    map_function: map_genero_to_dict

  - name: raca
    query_file: raca.sql
    schema_file: raca.json
    write_disposition: WRITE_TRUNCATE
    map_function: map_raca_to_dict