# ------------------------------------------------------------------
# Estágio 1: Imagem Base
# Usamos uma imagem oficial do Python 3.11, baseada em Debian (Bookworm).
# Ela é multi-plataforma, funcionando nativamente em amd64 e arm64 (M1/M2).
# ------------------------------------------------------------------
FROM python:3.11-slim-bookworm

# ------------------------------------------------------------------
# Metadados da Imagem
# ------------------------------------------------------------------
LABEL maintainer="Jonatas Onca <jonatas.onca@teconca.com>"
LABEL description="Imagem customizada para Dataflow Flex Template com base no Python 3.11."

# ------------------------------------------------------------------
# Instalação de Dependências do Sistema
# O Dataflow requer um Java Runtime Environment (JRE) para executar o runner.
# ------------------------------------------------------------------
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    # JRE é uma dependência crítica para o Apache Beam/Dataflow
    openjdk-17-jre-headless \
    && \
    # Limpeza para reduzir o tamanho da imagem
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ------------------------------------------------------------------
# Configuração do Ambiente da Aplicação
# ------------------------------------------------------------------
# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência primeiro para otimizar o cache do Docker
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# ------------------------------------------------------------------
# Cópia do Código da Aplicação
# ------------------------------------------------------------------
COPY main.py .
COPY setup.py .

# Cria o diretório para o driver JDBC e o copia
RUN mkdir -p _drivers
COPY _drivers/mysql-connector-j-8.0.33.jar _drivers/

# Cria um diretório para os módulos 'utils' e copia o conteúdo
COPY utils/ ./utils/

# ------------------------------------------------------------------
# Configuração para o Flex Template
# Estas variáveis de ambiente são Lidas pelo serviço do Dataflow
# para saber como iniciar seu pipeline.
# ------------------------------------------------------------------
ENV FLEX_TEMPLATE_PYTHON_PY_FILE=/app/main.py
ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=/app/requirements.txt
ENV FLEX_TEMPLATE_PYTHON_SETUP_FILE=/app/setup.py

# ENTRYPOINT ["python3", "/app/main.py"] # Descomente apenas para testes locais específicos.