# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Instale o Java (necessário para o ReadFromJdbc do Beam)
# CORREÇÃO: Usando openjdk-17, que está disponível na imagem base atual
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json

CMD ["python", "main.py"]