[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B", "W"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["beam_core"]
