--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ALT_ALU_ID AS CHAR) AS ALT_ALU_ID,
    CAST(ALT_ATIVO AS CHAR) AS ALT_ATIVO,
    CAST(ALT_BY_AVA_ONLINE AS CHAR) AS ALT_BY_AVA_ONLINE,
    CAST(ALT_BY_EDLER AS CHAR) AS ALT_BY_EDLER,
    CAST(ALT_BY_HERBY AS CHAR) AS ALT_BY_HERBY,
    CAST(ALT_DT_ATUALIZACAO AS CHAR) AS ALT_DT_ATUALIZACAO,
    CAST(ALT_DT_CRIACAO AS CHAR) AS ALT_DT_CRIACAO,
    CAST(ALT_FINALIZADO AS CHAR) AS ALT_FINALIZADO,
    CAST(ALT_FORNECEDOR AS CHAR) AS ALT_FORNECEDOR,
    CAST(ALT_ID AS CHAR) AS ALT_ID,
    CAST(ALT_JUSTIFICATIVA AS CHAR) AS ALT_JUSTIFICATIVA,
    CAST(ALT_TES_ID AS CHAR) AS ALT_TES_ID,
    CAST(ALT_USU_ID AS CHAR) AS ALT_USU_ID,
    CAST(schoolClassTURID AS CHAR) AS schoolClassTURID
FROM Saev.aluno_teste 