--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ALT_ALU_ID AS SIGNED) AS ALT_ALU_ID,
    CAST(ALT_ATIVO AS SIGNED) AS ALT_ATIVO,
    CAST(ALT_BY_AVA_ONLINE AS SIGNED) AS ALT_BY_AVA_ONLINE,
    CAST(ALT_BY_EDLER AS SIGNED) AS ALT_BY_EDLER,
    CAST(ALT_BY_HERBY AS SIGNED) AS ALT_BY_HERBY,
    CAST(ALT_DT_ATUALIZACAO AS CHAR) AS ALT_DT_ATUALIZACAO,
    CAST(ALT_DT_CRIACAO AS CHAR) AS ALT_DT_CRIACAO,
    CAST(ALT_FINALIZADO AS SIGNED) AS ALT_FINALIZADO,
    CAST(ALT_FORNECEDOR AS CHAR) AS ALT_FORNECEDOR,
    CAST(ALT_ID AS SIGNED) AS ALT_ID,
    CAST(ALT_JUSTIFICATIVA AS CHAR) AS ALT_JUSTIFICATIVA,
    CAST(ALT_TES_ID AS SIGNED) AS ALT_TES_ID,
    CAST(ALT_USU_ID AS SIGNED) AS ALT_USU_ID,
    CAST(schoolClassTURID AS SIGNED) AS schoolClassTURID
FROM Saev.aluno_teste limit 1