--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ATH_ALT_ID AS SIGNED) AS ATH_ALT_ID,
    CAST(ATH_ATR_ID AS SIGNED) AS ATH_ATR_ID,
    CAST(ATH_ATR_RESPOSTA_ANTIGA AS CHAR) AS ATH_ATR_RESPOSTA_ANTIGA,
    CAST(ATH_ATR_RESPOSTA_NOVA AS CHAR) AS ATH_ATR_RESPOSTA_NOVA,
    DATE_FORMAT(ATH_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS ATH_DT_CRIACAO,
    CAST(ATH_ID AS SIGNED) AS ATH_ID,
    CAST(ATH_OPERACAO AS CHAR) AS ATH_OPERACAO,
    CAST(ATH_TEG_ID AS SIGNED) AS ATH_TEG_ID
FROM Saev.aluno_teste_resposta_historico
