--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ANO_ATIVO AS CHAR) AS ANO_ATIVO,
    CAST(ANO_DT_ATUALIZACAO AS CHAR) AS ANO_DT_ATUALIZACAO,
    CAST(ANO_DT_CRIACAO AS CHAR) AS ANO_DT_CRIACAO,
    CAST(ANO_ID AS CHAR) AS ANO_ID,
    CAST(ANO_NOME AS CHAR) AS ANO_NOME,
    CAST(ANO_OLD_ID AS CHAR) AS ANO_OLD_ID
FROM Saev_Final.ano_letivo limit 1