--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ARE_ATIVO AS SIGNED) AS ARE_ATIVO,
    CAST(ARE_DESCRICAO AS CHAR) AS ARE_DESCRICAO,
    DATE_FORMAT(ARE_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS ARE_DT_ATUALIZACAO,
    DATE_FORMAT(ARE_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS ARE_DT_CRIACAO,
    CAST(ARE_ID AS SIGNED) AS ARE_ID,
    CAST(ARE_NOME AS CHAR) AS ARE_NOME
FROM Saev.area
