--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ARE_ATIVO AS CHAR) AS ARE_ATIVO,
    CAST(ARE_DESCRICAO AS CHAR) AS ARE_DESCRICAO,
    CAST(ARE_DT_ATUALIZACAO AS CHAR) AS ARE_DT_ATUALIZACAO,
    CAST(ARE_DT_CRIACAO AS CHAR) AS ARE_DT_CRIACAO,
    CAST(ARE_ID AS CHAR) AS ARE_ID,
    CAST(ARE_NOME AS CHAR) AS ARE_NOME
FROM Saev.area