--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ARQ_ATIVO AS SIGNED) AS ARQ_ATIVO,
    DATE_FORMAT(ARQ_DT_ATUALIZACAO, "") AS ARQ_DT_ATUALIZACAO,
    DATE_FORMAT(ARQ_DT_CRIACAO, "") AS ARQ_DT_CRIACAO,
    CAST(ARQ_ID AS SIGNED) AS ARQ_ID,
    CAST(ARQ_NOME AS CHAR) AS ARQ_NOME,
    CAST(ARQ_URL AS CHAR) AS ARQ_URL
FROM Saev.arquivo limit 1