--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(AVA_ANO AS CHAR) AS AVA_ANO,
    CAST(AVA_ATIVO AS SIGNED) AS AVA_ATIVO,
    DATE_FORMAT(AVA_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S.%f") AS AVA_DT_ATUALIZACAO,
    DATE_FORMAT(AVA_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS AVA_DT_CRIACAO,
    CAST(AVA_ID AS SIGNED) AS AVA_ID,
    CAST(AVA_NOME AS CHAR) AS AVA_NOME,
    CAST(AVA_OLD_ID AS SIGNED) AS AVA_OLD_ID
FROM Saev.avaliacao limit 1