--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(AVM_ATIVO AS SIGNED) AS AVM_ATIVO,
    CAST(AVM_AVA_ID AS SIGNED) AS AVM_AVA_ID,
    DATE_FORMAT(AVM_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S.%f") AS AVM_DT_ATUALIZACAO,
    DATE_FORMAT(AVM_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS AVM_DT_CRIACAO,
    DATE_FORMAT(AVM_DT_DISPONIVEL, "%Y-%m-%d %H:%M:%S") AS AVM_DT_DISPONIVEL,
    DATE_FORMAT(AVM_DT_FIM, "%Y-%m-%d %H:%M:%S") AS AVM_DT_FIM,
    DATE_FORMAT(AVM_DT_INICIO, "%Y-%m-%d %H:%M:%S") AS AVM_DT_INICIO,
    CAST(AVM_ID AS SIGNED) AS AVM_ID,
    CAST(AVM_MUN_ID AS SIGNED) AS AVM_MUN_ID,
    CAST(AVM_OLD_ID AS SIGNED) AS AVM_OLD_ID,
    CAST(AVM_TIPO AS CHAR) AS AVM_TIPO
FROM Saev.avaliacao_municipio limit 1