--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(AVA_ANO AS CHAR) AS AVA_ANO,
    CAST(AVA_ATIVO AS CHAR) AS AVA_ATIVO,
    CAST(AVA_DT_ATUALIZACAO AS CHAR) AS AVA_DT_ATUALIZACAO,
    CAST(AVA_DT_CRIACAO AS CHAR) AS AVA_DT_CRIACAO,
    CAST(AVA_ID AS CHAR) AS AVA_ID,
    CAST(AVA_NOME AS CHAR) AS AVA_NOME,
    CAST(AVA_OLD_ID AS CHAR) AS AVA_OLD_ID
FROM Saev.avaliacao 