--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(AVM_ATIVO AS CHAR) AS AVM_ATIVO,
    CAST(AVM_AVA_ID AS CHAR) AS AVM_AVA_ID,
    CAST(AVM_DT_ATUALIZACAO AS CHAR) AS AVM_DT_ATUALIZACAO,
    CAST(AVM_DT_CRIACAO AS CHAR) AS AVM_DT_CRIACAO,
    CAST(AVM_DT_DISPONIVEL AS CHAR) AS AVM_DT_DISPONIVEL,
    CAST(AVM_DT_FIM AS CHAR) AS AVM_DT_FIM,
    CAST(AVM_DT_INICIO AS CHAR) AS AVM_DT_INICIO,
    CAST(AVM_ID AS CHAR) AS AVM_ID,
    CAST(AVM_MUN_ID AS CHAR) AS AVM_MUN_ID,
    CAST(AVM_OLD_ID AS CHAR) AS AVM_OLD_ID,
    CAST(AVM_TIPO AS CHAR) AS AVM_TIPO
FROM Saev.avaliacao_municipio limit 1