--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(DAT_ARQUIVO AS CHAR) AS DAT_ARQUIVO,
    DATE_FORMAT(DAT_DT_ATUALIZACAO, "") AS DAT_DT_ATUALIZACAO,
    DATE_FORMAT(DAT_DT_CRIACAO, "") AS DAT_DT_CRIACAO,
    CAST(DAT_ID AS SIGNED) AS DAT_ID,
    CAST(DAT_NOME AS CHAR) AS DAT_NOME,
    CAST(DAT_OBS AS CHAR) AS DAT_OBS,
    CAST(DAT_STATUS AS CHAR) AS DAT_STATUS,
    CAST(DAT_TIPO AS CHAR) AS DAT_TIPO,
    CAST(DAT_USU_ID AS SIGNED) AS DAT_USU_ID
FROM Saev.dados limit 1