--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(DIS_ATIVO AS CHAR) AS DIS_ATIVO,
    CAST(DIS_COLOR AS CHAR) AS DIS_COLOR,
    CAST(DIS_DT_ATUALIZACAO AS CHAR) AS DIS_DT_ATUALIZACAO,
    CAST(DIS_DT_CRIACAO AS CHAR) AS DIS_DT_CRIACAO,
    CAST(DIS_ID AS CHAR) AS DIS_ID,
    CAST(DIS_NOME AS CHAR) AS DIS_NOME,
    CAST(DIS_OLD_ID AS CHAR) AS DIS_OLD_ID,
    CAST(DIS_TIPO AS CHAR) AS DIS_TIPO
FROM Saev.disciplina