--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(DIS_ATIVO AS SIGNED) AS DIS_ATIVO,
    CAST(DIS_COLOR AS CHAR) AS DIS_COLOR,
    DATE_FORMAT(DIS_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS DIS_DT_ATUALIZACAO,
    DATE_FORMAT(DIS_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS DIS_DT_CRIACAO,
    CAST(DIS_ID AS SIGNED) AS DIS_ID,
    CAST(DIS_NOME AS CHAR) AS DIS_NOME,
    CAST(DIS_OLD_ID AS SIGNED) AS DIS_OLD_ID,
    CAST(DIS_TIPO AS CHAR) AS DIS_TIPO
FROM Saev.disciplina
