--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(ESC_ATIVO AS SIGNED) AS ESC_ATIVO,
    CAST(ESC_BAIRRO AS CHAR) AS ESC_BAIRRO,
    CAST(ESC_CEP AS CHAR) AS ESC_CEP,
    CAST(ESC_CIDADE AS CHAR) AS ESC_CIDADE,
    CAST(ESC_COMPLEMENTO AS CHAR) AS ESC_COMPLEMENTO,
    DATE_FORMAT(ESC_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS ESC_DT_ATUALIZACAO,
    DATE_FORMAT(ESC_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS ESC_DT_CRIACAO,
    CAST(ESC_ENDERECO AS CHAR) AS ESC_ENDERECO,
    CAST(ESC_ID AS SIGNED) AS ESC_ID,
    CAST(ESC_INEP AS CHAR) AS ESC_INEP,
    CAST(ESC_INTEGRAL AS SIGNED) AS ESC_INTEGRAL,
    CAST(ESC_LOGO AS CHAR) AS ESC_LOGO,
    CAST(ESC_MUN_ID AS SIGNED) AS ESC_MUN_ID,
    CAST(ESC_NOME AS CHAR) AS ESC_NOME,
    CAST(ESC_NUMERO AS CHAR) AS ESC_NUMERO,
    CAST(ESC_OLD_ID AS SIGNED) AS ESC_OLD_ID,
    CAST(ESC_STATUS AS CHAR) AS ESC_STATUS,
    CAST(ESC_TIPO AS CHAR) AS ESC_TIPO,
    CAST(ESC_UF AS CHAR) AS ESC_UF,
    CAST(regionalId AS SIGNED) AS regionalId
FROM Saev.escola
