--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(FOR_ATIVO AS SIGNED) AS FOR_ATIVO,
    DATE_FORMAT(FOR_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS FOR_DT_ATUALIZACAO,
    DATE_FORMAT(FOR_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS FOR_DT_CRIACAO,
    CAST(FOR_ID AS SIGNED) AS FOR_ID,
    CAST(FOR_NOME AS CHAR) AS FOR_NOME
FROM Saev.formacao
