--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(FOR_ATIVO AS SIGNED) AS FOR_ATIVO,
    CAST(FOR_DT_ATUALIZACAO AS CHAR) AS FOR_DT_ATUALIZACAO,
    CAST(FOR_DT_CRIACAO AS CHAR) AS FOR_DT_CRIACAO,
    CAST(FOR_ID AS SIGNED) AS FOR_ID,
    CAST(FOR_NOME AS CHAR) AS FOR_NOME
FROM Saev.formacao limit 1