--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(GEN_ATIVO AS CHAR) AS GEN_ATIVO,
    CAST(GEN_DT_ATUALIZACAO AS CHAR) AS GEN_DT_ATUALIZACAO,
    CAST(GEN_DT_CRIACAO AS CHAR) AS GEN_DT_CRIACAO,
    CAST(GEN_ID AS CHAR) AS GEN_ID,
    CAST(GEN_NOME AS CHAR) AS GEN_NOME
FROM Saev_Final.genero limit 1