--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(GEN_ATIVO AS SIGNED) AS GEN_ATIVO,
    STR_TO_DATE(GEN_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS GEN_DT_ATUALIZACAO,
    STR_TO_DATE(GEN_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS GEN_DT_CRIACAO,
    CAST(GEN_ID AS SIGNED) AS GEN_ID,
    CAST(GEN_NOME AS CHAR) AS GEN_NOME
FROM Saev.genero
