--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(DAT_ARQUIVO_ERROR_URL AS CHAR) AS DAT_ARQUIVO_ERROR_URL,
    CAST(DAT_ARQUIVO_URL AS CHAR) AS DAT_ARQUIVO_URL,
    DATE_FORMAT(DAT_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S") AS DAT_DT_ATUALIZACAO,
    DATE_FORMAT(DAT_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS DAT_DT_CRIACAO,
    CAST(DAT_ID AS SIGNED) AS DAT_ID,
    CAST(DAT_NOME AS CHAR) AS DAT_NOME,
    CAST(DAT_OBS AS CHAR) AS DAT_OBS,
    CAST(DAT_STATUS AS CHAR) AS DAT_STATUS,
    CAST(dATUSUUSUID AS SIGNED) AS dATUSUUSUID
FROM Saev.importar_dados limit 1