--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(IFR_ALU_ID AS SIGNED) AS IFR_ALU_ID,
    CAST(IFR_ANO AS SIGNED) AS IFR_ANO,
    CAST(IFR_DT_ATUALIZACAO AS CHAR) AS IFR_DT_ATUALIZACAO,
    CAST(IFR_DT_CRIACAO AS CHAR) AS IFR_DT_CRIACAO,
    CAST(IFR_FALTA AS SIGNED) AS IFR_FALTA,
    CAST(IFR_ID AS SIGNED) AS IFR_ID,
    CAST(IFR_MES AS SIGNED) AS IFR_MES,
    CAST(IFR_OLD_ID AS SIGNED) AS IFR_OLD_ID,
    CAST(IFR_SCHOOL_CLASS_ID AS SIGNED) AS IFR_SCHOOL_CLASS_ID
FROM Saev.infrequencia limit 1