--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(IFR_ALU_ID AS SIGNED) AS IFR_ALU_ID,
    CAST(IFR_ANO AS SIGNED) AS IFR_ANO,
    DATE_FORMAT(IFR_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S.%f") AS IFR_DT_ATUALIZACAO,
    DATE_FORMAT(IFR_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS IFR_DT_CRIACAO,
    CAST(IFR_FALTA AS SIGNED) AS IFR_FALTA,
    CAST(IFR_ID AS SIGNED) AS IFR_ID,
    CAST(IFR_MES AS SIGNED) AS IFR_MES,
    CAST(IFR_OLD_ID AS SIGNED) AS IFR_OLD_ID,
    CAST(IFR_SCHOOL_CLASS_ID AS SIGNED) AS IFR_SCHOOL_CLASS_ID
FROM Saev.infrequencia limit 1