--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MTI_ATIVO AS SIGNED) AS MTI_ATIVO,
    CAST(MTI_CODIGO AS CHAR) AS MTI_CODIGO,
    CAST(MTI_DESCRITOR AS CHAR) AS MTI_DESCRITOR,
    CAST(MTI_DT_ATUALIZACAO AS CHAR) AS MTI_DT_ATUALIZACAO,
    CAST(MTI_DT_CRIACAO AS CHAR) AS MTI_DT_CRIACAO,
    CAST(MTI_ID AS SIGNED) AS MTI_ID,
    CAST(MTI_MTO_ID AS SIGNED) AS MTI_MTO_ID,
    CAST(MTI_OLD_ID AS SIGNED) AS MTI_OLD_ID
FROM Saev.matriz_referencia_topico_items limit 1