--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MAR_ATIVO AS SIGNED) AS MAR_ATIVO,
    CAST(MAR_DIS_ID AS SIGNED) AS MAR_DIS_ID,
    DATE_FORMAT(MAR_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S") AS MAR_DT_ATUALIZACAO,
    DATE_FORMAT(MAR_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS MAR_DT_CRIACAO,
    CAST(MAR_ID AS SIGNED) AS MAR_ID,
    CAST(MAR_NOME AS CHAR) AS MAR_NOME,
    CAST(MAR_OLD_ID AS SIGNED) AS MAR_OLD_ID
FROM Saev.matriz_referencia limit 1