--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MTO_ATIVO AS SIGNED) AS MTO_ATIVO,
    DATE_FORMAT(MTO_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS MTO_DT_ATUALIZACAO,
    DATE_FORMAT(MTO_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS MTO_DT_CRIACAO,
    CAST(MTO_ID AS SIGNED) AS MTO_ID,
    CAST(MTO_MAR_ID AS SIGNED) AS MTO_MAR_ID,
    CAST(MTO_NOME AS CHAR) AS MTO_NOME,
    CAST(MTO_OLD_ID AS SIGNED) AS MTO_OLD_ID
FROM Saev.matriz_referencia_topico
