--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MTO_ATIVO AS CHAR) AS MTO_ATIVO,
    CAST(MTO_DT_ATUALIZACAO AS CHAR) AS MTO_DT_ATUALIZACAO,
    CAST(MTO_DT_CRIACAO AS CHAR) AS MTO_DT_CRIACAO,
    CAST(MTO_ID AS CHAR) AS MTO_ID,
    CAST(MTO_MAR_ID AS CHAR) AS MTO_MAR_ID,
    CAST(MTO_NOME AS CHAR) AS MTO_NOME,
    CAST(MTO_OLD_ID AS CHAR) AS MTO_OLD_ID
FROM Saev.matriz_referencia_topico limit 100