--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MAR_ATIVO AS CHAR) AS MAR_ATIVO,
    CAST(MAR_DIS_ID AS CHAR) AS MAR_DIS_ID,
    CAST(MAR_DT_ATUALIZACAO AS CHAR) AS MAR_DT_ATUALIZACAO,
    CAST(MAR_DT_CRIACAO AS CHAR) AS MAR_DT_CRIACAO,
    CAST(MAR_ID AS CHAR) AS MAR_ID,
    CAST(MAR_NOME AS CHAR) AS MAR_NOME,
    CAST(MAR_OLD_ID AS CHAR) AS MAR_OLD_ID
FROM Saev.matriz_referencia