--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MUN_ARQ_CONVENIO AS CHAR) AS MUN_ARQ_CONVENIO,
    CAST(MUN_ATIVO AS SIGNED) AS MUN_ATIVO,
    CAST(MUN_BAIRRO AS CHAR) AS MUN_BAIRRO,
    CAST(MUN_CEP AS CHAR) AS MUN_CEP,
    CAST(MUN_CIDADE AS CHAR) AS MUN_CIDADE,
    CAST(MUN_COD_IBGE AS SIGNED) AS MUN_COD_IBGE,
    CAST(MUN_COMPARTILHAR_DADOS AS SIGNED) AS MUN_COMPARTILHAR_DADOS,
    CAST(MUN_COMPLEMENTO AS CHAR) AS MUN_COMPLEMENTO,
    DATE_FORMAT(MUN_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS MUN_DT_ATUALIZACAO,
    DATE_FORMAT(MUN_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS MUN_DT_CRIACAO,
    DATE_FORMAT(MUN_DT_FIM, "%Y-%m-%d %H:%i:%s.%f") AS MUN_DT_FIM,
    DATE_FORMAT(MUN_DT_INICIO, "%Y-%m-%d %H:%i:%s.%f") AS MUN_DT_INICIO,
    CAST(MUN_ENDERECO AS CHAR) AS MUN_ENDERECO,
    CAST(MUN_ID AS SIGNED) AS MUN_ID,
    CAST(MUN_LOGO AS CHAR) AS MUN_LOGO,
    CAST(MUN_MENSAGEM_EMAIL_ATIVO AS SIGNED) AS MUN_MENSAGEM_EMAIL_ATIVO,
    CAST(MUN_MENSAGEM_WHATSAPP_ATIVO AS SIGNED) AS MUN_MENSAGEM_WHATSAPP_ATIVO,
    CAST(MUN_NOME AS CHAR) AS MUN_NOME,
    CAST(MUN_NUMERO AS CHAR) AS MUN_NUMERO,
    CAST(MUN_OLD_ID AS SIGNED) AS MUN_OLD_ID,
    CAST(MUN_PARCEIRO_EPV AS SIGNED) AS MUN_PARCEIRO_EPV,
    CAST(MUN_STATUS AS CHAR) AS MUN_STATUS,
    CAST(MUN_UF AS CHAR) AS MUN_UF,
    CAST(stateId AS SIGNED) AS stateId,
    CAST(stateRegionalId AS SIGNED) AS stateRegionalId
FROM Saev.municipio
