--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(MUN_ARQ_CONVENIO AS CHAR) AS MUN_ARQ_CONVENIO,
    CAST(MUN_ATIVO AS CHAR) AS MUN_ATIVO,
    CAST(MUN_BAIRRO AS CHAR) AS MUN_BAIRRO,
    CAST(MUN_CEP AS CHAR) AS MUN_CEP,
    CAST(MUN_CIDADE AS CHAR) AS MUN_CIDADE,
    CAST(MUN_COD_IBGE AS CHAR) AS MUN_COD_IBGE,
    CAST(MUN_COMPARTILHAR_DADOS AS CHAR) AS MUN_COMPARTILHAR_DADOS,
    CAST(MUN_COMPLEMENTO AS CHAR) AS MUN_COMPLEMENTO,
    CAST(MUN_DT_ATUALIZACAO AS CHAR) AS MUN_DT_ATUALIZACAO,
    CAST(MUN_DT_CRIACAO AS CHAR) AS MUN_DT_CRIACAO,
    CAST(MUN_DT_FIM AS CHAR) AS MUN_DT_FIM,
    CAST(MUN_DT_INICIO AS CHAR) AS MUN_DT_INICIO,
    CAST(MUN_ENDERECO AS CHAR) AS MUN_ENDERECO,
    CAST(MUN_ID AS CHAR) AS MUN_ID,
    CAST(MUN_LOGO AS CHAR) AS MUN_LOGO,
    CAST(MUN_MENSAGEM_EMAIL_ATIVO AS CHAR) AS MUN_MENSAGEM_EMAIL_ATIVO,
    CAST(MUN_MENSAGEM_WHATSAPP_ATIVO AS CHAR) AS MUN_MENSAGEM_WHATSAPP_ATIVO,
    CAST(MUN_NOME AS CHAR) AS MUN_NOME,
    CAST(MUN_NUMERO AS CHAR) AS MUN_NUMERO,
    CAST(MUN_OLD_ID AS CHAR) AS MUN_OLD_ID,
    CAST(MUN_PARCEIRO_EPV AS CHAR) AS MUN_PARCEIRO_EPV,
    CAST(MUN_STATUS AS CHAR) AS MUN_STATUS,
    CAST(MUN_UF AS CHAR) AS MUN_UF,
    CAST(stateId AS CHAR) AS stateId,
    CAST(stateRegionalId AS CHAR) AS stateRegionalId
FROM Saev.municipio 