--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(PCD_ATIVO AS SIGNED) AS PCD_ATIVO,
    DATE_FORMAT(PCD_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS PCD_DT_ATUALIZACAO,
    DATE_FORMAT(PCD_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS PCD_DT_CRIACAO,
    CAST(PCD_ID AS SIGNED) AS PCD_ID,
    CAST(PCD_NOME AS CHAR) AS PCD_NOME,
    CAST(PCD_OLD_ID AS SIGNED) AS PCD_OLD_ID
FROM Saev.pcd
