--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(PER_ATIVO AS SIGNED) AS PER_ATIVO,
    CAST(PER_DT_ATUALIZACAO AS CHAR) AS PER_DT_ATUALIZACAO,
    CAST(PER_DT_CRIACAO AS CHAR) AS PER_DT_CRIACAO,
    CAST(PER_ID AS SIGNED) AS PER_ID,
    CAST(PER_NOME AS CHAR) AS PER_NOME
FROM Saev.perfil_base limit 1