--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(PRO_ATIVO AS SIGNED) AS PRO_ATIVO,
    CAST(PRO_AVATAR AS CHAR) AS PRO_AVATAR,
    CAST(PRO_BAIRRO AS CHAR) AS PRO_BAIRRO,
    CAST(PRO_CEP AS CHAR) AS PRO_CEP,
    CAST(PRO_CIDADE AS CHAR) AS PRO_CIDADE,
    CAST(PRO_COMPLEMENTO AS CHAR) AS PRO_COMPLEMENTO,
    CAST(PRO_DOCUMENTO AS CHAR) AS PRO_DOCUMENTO,
    DATE_FORMAT(PRO_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS PRO_DT_ATUALIZACAO,
    DATE_FORMAT(PRO_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS PRO_DT_CRIACAO,
    DATE_FORMAT(PRO_DT_NASC, "%Y-%m-%d %H:%i:%s.%f") AS PRO_DT_NASC,
    CAST(PRO_EMAIL AS CHAR) AS PRO_EMAIL,
    CAST(PRO_ENDERECO AS CHAR) AS PRO_ENDERECO,
    CAST(PRO_FONE AS CHAR) AS PRO_FONE,
    CAST(PRO_FOR_ID AS SIGNED) AS PRO_FOR_ID,
    CAST(PRO_GEN_ID AS SIGNED) AS PRO_GEN_ID,
    CAST(PRO_ID AS SIGNED) AS PRO_ID,
    CAST(PRO_MUN_ID AS SIGNED) AS PRO_MUN_ID,
    CAST(PRO_NOME AS CHAR) AS PRO_NOME,
    CAST(PRO_NUMERO AS CHAR) AS PRO_NUMERO,
    CAST(PRO_OLD_ID AS SIGNED) AS PRO_OLD_ID,
    CAST(PRO_PEL_ID AS SIGNED) AS PRO_PEL_ID,
    CAST(PRO_UF AS CHAR) AS PRO_UF
FROM Saev.professor
