--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(PEL_ATIVO AS SIGNED) AS PEL_ATIVO,
    DATE_FORMAT(PEL_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S") AS PEL_DT_ATUALIZACAO,
    DATE_FORMAT(PEL_DT_CRIACAO, "%Y-%m-%d %H:%M:%S") AS PEL_DT_CRIACAO,
    CAST(PEL_ID AS SIGNED) AS PEL_ID,
    CAST(PEL_NOME AS CHAR) AS PEL_NOME,
    CAST(PEL_OLD_ID AS SIGNED) AS PEL_OLD_ID
FROM Saev.raca limit 1