--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(PEL_ATIVO AS UNSIGNED) AS PEL_ATIVO, 
    CAST(PEL_ID AS SIGNED) AS PEL_ID, 
    CAST(PEL_NOME AS CHAR) AS PEL_NOME, 
    CAST(PEL_OLD_ID AS SIGNED) AS PEL_OLD_ID
FROM raca
