--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(PEL_ATIVO AS CHAR) AS PEL_ATIVO,
    CAST(PEL_DT_ATUALIZACAO AS CHAR) AS PEL_DT_ATUALIZACAO,
    CAST(PEL_DT_CRIACAO AS CHAR) AS PEL_DT_CRIACAO,
    CAST(PEL_ID AS CHAR) AS PEL_ID,
    CAST(PEL_NOME AS CHAR) AS PEL_NOME,
    CAST(PEL_OLD_ID AS CHAR) AS PEL_OLD_ID
FROM Saev.raca