--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(SER_ATIVO AS CHAR) AS SER_ATIVO,
    CAST(SER_DT_ATUALIZACAO AS CHAR) AS SER_DT_ATUALIZACAO,
    CAST(SER_DT_CRIACAO AS CHAR) AS SER_DT_CRIACAO,
    CAST(SER_ID AS CHAR) AS SER_ID,
    CAST(SER_NOME AS CHAR) AS SER_NOME,
    CAST(SER_NUMBER AS CHAR) AS SER_NUMBER,
    CAST(SER_OLD_ID AS CHAR) AS SER_OLD_ID
FROM Saev.series limit 100