--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(SER_ATIVO AS SIGNED) AS SER_ATIVO,
    DATE_FORMAT(SER_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS SER_DT_ATUALIZACAO,
    DATE_FORMAT(SER_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS SER_DT_CRIACAO,
    CAST(SER_ID AS SIGNED) AS SER_ID,
    CAST(SER_NOME AS CHAR) AS SER_NOME,
    CAST(SER_NUMBER AS SIGNED) AS SER_NUMBER,
    CAST(SER_OLD_ID AS SIGNED) AS SER_OLD_ID
FROM Saev.series
