--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(SPE_ATIVO AS SIGNED) AS SPE_ATIVO,
    DATE_FORMAT(SPE_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S.%f") AS SPE_DT_ATUALIZACAO,
    DATE_FORMAT(SPE_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS SPE_DT_CRIACAO,
    CAST(SPE_ID AS SIGNED) AS SPE_ID,
    CAST(SPE_NOME AS CHAR) AS SPE_NOME,
    CAST(SPE_PER_ID AS SIGNED) AS SPE_PER_ID,
    CAST(role AS CHAR) AS role
FROM Saev.sub_perfil limit 1