--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    DATE_FORMAT(TEG_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S") AS TEG_DT_ATUALIZACAO,
    DATE_FORMAT(TEG_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS TEG_DT_CRIACAO,
    CAST(TEG_ID AS SIGNED) AS TEG_ID,
    CAST(TEG_MTI_ID AS SIGNED) AS TEG_MTI_ID,
    CAST(TEG_OLD_ID AS SIGNED) AS TEG_OLD_ID,
    CAST(TEG_ORDEM AS SIGNED) AS TEG_ORDEM,
    CAST(TEG_RESPOSTA_CORRETA AS CHAR) AS TEG_RESPOSTA_CORRETA,
    CAST(TEG_TES_ID AS SIGNED) AS TEG_TES_ID
FROM Saev.teste_gabarito limit 1