--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(TES_ANO AS CHAR) AS TES_ANO,
    CAST(TES_ARQUIVO AS CHAR) AS TES_ARQUIVO,
    CAST(TES_ATIVO AS SIGNED) AS TES_ATIVO,
    CAST(TES_DIS_ID AS SIGNED) AS TES_DIS_ID,
    DATE_FORMAT(TES_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS TES_DT_ATUALIZACAO,
    DATE_FORMAT(TES_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS TES_DT_CRIACAO,
    CAST(TES_ID AS SIGNED) AS TES_ID,
    CAST(TES_MANUAL AS CHAR) AS TES_MANUAL,
    CAST(TES_MAR_ID AS SIGNED) AS TES_MAR_ID,
    CAST(TES_NOME AS CHAR) AS TES_NOME,
    CAST(TES_OLD_ID AS SIGNED) AS TES_OLD_ID,
    CAST(TES_SER_ID AS SIGNED) AS TES_SER_ID,
    CAST(assessmentOnlineId AS SIGNED) AS assessmentOnlineId,
    CAST(assessmentOnlineId AS SIGNED) AS assessmentOnlineId
FROM Saev.teste
