--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(TES_ANO AS CHAR) AS TES_ANO,
    CAST(TES_ARQUIVO AS CHAR) AS TES_ARQUIVO,
    CAST(TES_ATIVO AS CHAR) AS TES_ATIVO,
    CAST(TES_DIS_ID AS CHAR) AS TES_DIS_ID,
    CAST(TES_DT_ATUALIZACAO AS CHAR) AS TES_DT_ATUALIZACAO,
    CAST(TES_DT_CRIACAO AS CHAR) AS TES_DT_CRIACAO,
    CAST(TES_ID AS CHAR) AS TES_ID,
    CAST(TES_MANUAL AS CHAR) AS TES_MANUAL,
    CAST(TES_MAR_ID AS CHAR) AS TES_MAR_ID,
    CAST(TES_NOME AS CHAR) AS TES_NOME,
    CAST(TES_OLD_ID AS CHAR) AS TES_OLD_ID,
    CAST(TES_SER_ID AS CHAR) AS TES_SER_ID,
    CAST(assessmentOnlineId AS CHAR) AS assessmentOnlineId
FROM Saev.teste limit 1