--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(TRF_ALU_ID AS SIGNED) AS TRF_ALU_ID,
    DATE_FORMAT(TRF_DT_ATUALIZACAO, "%Y-%m-%d %H:%i:%s.%f") AS TRF_DT_ATUALIZACAO,
    DATE_FORMAT(TRF_DT_CRIACAO, "%Y-%m-%d %H:%i:%s.%f") AS TRF_DT_CRIACAO,
    CAST(TRF_ESC_ID_DESTINO AS SIGNED) AS TRF_ESC_ID_DESTINO,
    CAST(TRF_ESC_ID_ORIGEM AS SIGNED) AS TRF_ESC_ID_ORIGEM,
    CAST(TRF_ID AS SIGNED) AS TRF_ID,
    CAST(TRF_JUSTIFICATIVA AS CHAR) AS TRF_JUSTIFICATIVA,
    CAST(TRF_OLD_ID AS SIGNED) AS TRF_OLD_ID,
    CAST(TRF_STATUS AS CHAR) AS TRF_STATUS,
    CAST(TRF_TUR_ID_DESTINO AS SIGNED) AS TRF_TUR_ID_DESTINO,
    CAST(TRF_TUR_ID_ORIGEM AS SIGNED) AS TRF_TUR_ID_ORIGEM,
    CAST(TRF_USU AS SIGNED) AS TRF_USU,
    CAST(TRF_USU_STATUS AS SIGNED) AS TRF_USU_STATUS
FROM Saev.transferencia
