--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(TRF_ALU_ID AS CHAR) AS TRF_ALU_ID,
    CAST(TRF_DT_ATUALIZACAO AS CHAR) AS TRF_DT_ATUALIZACAO,
    CAST(TRF_DT_CRIACAO AS CHAR) AS TRF_DT_CRIACAO,
    CAST(TRF_ESC_ID_DESTINO AS CHAR) AS TRF_ESC_ID_DESTINO,
    CAST(TRF_ESC_ID_ORIGEM AS CHAR) AS TRF_ESC_ID_ORIGEM,
    CAST(TRF_ID AS CHAR) AS TRF_ID,
    CAST(TRF_JUSTIFICATIVA AS CHAR) AS TRF_JUSTIFICATIVA,
    CAST(TRF_OLD_ID AS CHAR) AS TRF_OLD_ID,
    CAST(TRF_STATUS AS CHAR) AS TRF_STATUS,
    CAST(TRF_TUR_ID_DESTINO AS CHAR) AS TRF_TUR_ID_DESTINO,
    CAST(TRF_TUR_ID_ORIGEM AS CHAR) AS TRF_TUR_ID_ORIGEM,
    CAST(TRF_USU AS CHAR) AS TRF_USU,
    CAST(TRF_USU_STATUS AS CHAR) AS TRF_USU_STATUS
FROM Saev.transferencia limit 1