--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(TUR_ANEXO AS SIGNED) AS TUR_ANEXO,
    CAST(TUR_ANO AS CHAR) AS TUR_ANO,
    CAST(TUR_ATIVO AS SIGNED) AS TUR_ATIVO,
    DATE_FORMAT(TUR_DT_ATUALIZACAO, "%Y-%m-%d %H:%M:%S") AS TUR_DT_ATUALIZACAO,
    DATE_FORMAT(TUR_DT_CRIACAO, "%Y-%m-%d %H:%M:%S.%f") AS TUR_DT_CRIACAO,
    CAST(TUR_ESC_ID AS SIGNED) AS TUR_ESC_ID,
    CAST(TUR_ID AS SIGNED) AS TUR_ID,
    CAST(TUR_MUN_ID AS SIGNED) AS TUR_MUN_ID,
    CAST(TUR_NOME AS CHAR) AS TUR_NOME,
    CAST(TUR_OLD_ID AS SIGNED) AS TUR_OLD_ID,
    CAST(TUR_PERIODO AS CHAR) AS TUR_PERIODO,
    CAST(TUR_SER_ID AS SIGNED) AS TUR_SER_ID,
    CAST(TUR_TIPO AS CHAR) AS TUR_TIPO
FROM Saev.turma limit 1