--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(TUR_ANEXO AS CHAR) AS TUR_ANEXO,
    CAST(TUR_ANO AS CHAR) AS TUR_ANO,
    CAST(TUR_ATIVO AS CHAR) AS TUR_ATIVO,
    CAST(TUR_DT_ATUALIZACAO AS CHAR) AS TUR_DT_ATUALIZACAO,
    CAST(TUR_DT_CRIACAO AS CHAR) AS TUR_DT_CRIACAO,
    CAST(TUR_ESC_ID AS CHAR) AS TUR_ESC_ID,
    CAST(TUR_ID AS CHAR) AS TUR_ID,
    CAST(TUR_MUN_ID AS CHAR) AS TUR_MUN_ID,
    CAST(TUR_NOME AS CHAR) AS TUR_NOME,
    CAST(TUR_OLD_ID AS CHAR) AS TUR_OLD_ID,
    CAST(TUR_PERIODO AS CHAR) AS TUR_PERIODO,
    CAST(TUR_SER_ID AS CHAR) AS TUR_SER_ID,
    CAST(TUR_TIPO AS CHAR) AS TUR_TIPO
FROM Saev.turma