--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    CAST(USU_ATIVO AS SIGNED) AS USU_ATIVO,
    CAST(USU_AVATAR AS CHAR) AS USU_AVATAR,
    CAST(USU_DOCUMENTO AS CHAR) AS USU_DOCUMENTO,
    CAST(USU_DT_ATUALIZACAO AS CHAR) AS USU_DT_ATUALIZACAO,
    CAST(USU_DT_CRIACAO AS CHAR) AS USU_DT_CRIACAO,
    CAST(USU_EMAIL AS CHAR) AS USU_EMAIL,
    CAST(USU_ESC_ID AS SIGNED) AS USU_ESC_ID,
    CAST(USU_FONE AS CHAR) AS USU_FONE,
    CAST(USU_ID AS SIGNED) AS USU_ID,
    CAST(USU_MUN_ID AS SIGNED) AS USU_MUN_ID,
    CAST(USU_NOME AS CHAR) AS USU_NOME,
    CAST(USU_SENHA AS CHAR) AS USU_SENHA,
    CAST(USU_SPE_ID AS SIGNED) AS USU_SPE_ID,
    CAST(isChangePasswordWelcome AS SIGNED) AS isChangePasswordWelcome,
    CAST(stateId AS SIGNED) AS stateId
FROM Saev.usuario limit 1